# Generated by Django 3.2.25 on 2026-03-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_roommessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Career',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
