# Generated by Django 3.2.25 on 2026-04-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20260326_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='audience_type',
            field=models.CharField(choices=[('All', 'All'), ('Senior', 'Senior Only'), ('Junior', 'Junior Only')], default='All', max_length=10),
        ),
        migrations.AddField(
            model_name='announcement',
            name='department',
            field=models.CharField(choices=[('HR', 'HR'), ('IT', 'IT'), ('FINANCE', 'Finance')], default='HR', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='section',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='seniority',
            field=models.CharField(choices=[('Senior', 'Senior'), ('Junior', 'Junior')], default='Junior', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('HR', 'HR'), ('IT', 'IT'), ('FINANCE', 'Finance')], default='HR', max_length=20),
        ),
    ]
