# Generated by Django 3.2.25 on 2026-04-17 03:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_group_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to_department',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('IT', 'IT'), ('FINANCE', 'Finance')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='department_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
